version: "3.4"

services:
  customflask:
    image: sysvador-debug
    build:
      context: .
      dockerfile: ./Dockerfile
      target: debug
    command:
      [
        "sh",
        "-c",
        "pip install debugpy -t /tmp && python /tmp/debugpy --wait-for-client --listen 0.0.0.0:5678 -m flask run --no-debugger --no-reload --host 0.0.0.0 --port 5002",
      ]
    ports:
      - 5002:5002
      - 5678:5678
    volumes:
      - type: bind
        source: ./sysvador
        target: /app/sysvador
    environment:
      - FLASK_APP=sysvador/app.py
      - FLASK_ENV=development
